/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testInsertionSort() {
        Library classUnderTest = new Library();

        int [] arr = {13,3,4,7,8,20,32,1};
        classUnderTest.insertionSort(arr);
        assertEquals(arr,classUnderTest.insertionSort(arr));
    }

    @Test void testMergeSort() {
        Library classUnderTest = new Library();

        int[] arr = {13, 3, 4, 7, 8, 20, 32, 1};
        classUnderTest.mergeSort(arr);

        for (int i = 0; i < arr.length -1; i++) {
            assertTrue(arr[i] < arr[i+1],"true");
        }
    }
}
