/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testInsertionSort() {
        Library classUnderTest = new Library();

        int [] arr = {13,3,4,7,8,20,32,1};
        classUnderTest.insertionSort(arr);
        assertEquals(arr,classUnderTest.insertionSort(arr));
    }

    @Test void testMergeSort() {
        Library classUnderTest = new Library();

        int[] arr = {13, 3, 4, 7, 8, 20, 32, 1};
        classUnderTest.mergeSort(arr);

        for (int i = 0; i < arr.length -1; i++) {
            assertTrue(arr[i] < arr[i+1],"true");
        }
    }
    @Test void TestQuickSort() {

        Library classUnderTest = new Library();

        int[] arr={1,7,3,-1,9,10};
        classUnderTest.QuickSort(arr,0,arr.length-1);
        assertEquals("[-1, 1, 3, 7, 9, 10]", Arrays.toString(arr));
    }
}
