/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.data;

public class LinkListNode {
    public boolean someLibraryMethod() {
        return true;
    }

    private String data;
    private LinkListNode next;

    public LinkListNode(String data) {
        this.data = data;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public LinkListNode getNext() {
        return next;
    }

    public void setNext(LinkListNode next) {
        this.next = next;
    }

    @Override
    public String toString() {
        return data;
    }
}
