/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HashTableTest {

    HashTable<String, Integer> hashTable = new HashTable<>();

    @Test
    public void addingTest(){
        hashTable.add("Test",10);
        assertTrue(hashTable.contains("Test"));
    }

    @Test
    public void getTest(){
        hashTable.add("Test",10);
        assertEquals(10,hashTable.get("Test"));
    }

    @Test
    public void testNull(){
        hashTable.add("Test",10);
        assertNull(hashTable.get("notTest"));
    }

    @Test
    public void handleCollision(){
        hashTable.add("Test1",10);
        hashTable.add("Test2",20);
        hashTable.add("Test3",30);
        hashTable.add("Test4",40);

        assertEquals(4,hashTable.getSize());
    }

    @Test
    public void retrieveFromCollision(){
        hashTable.add("Test1",10);
        hashTable.add("Test2",20);
        hashTable.add("Test3",30);
        hashTable.add("Test4",40);
        hashTable.add("Test1",10);
        hashTable.add("Test2",20);
        hashTable.add("Test3",30);
        hashTable.add("Test4",40);

        assertEquals(40,hashTable.get("Test4"));
    }


    @Test
    public void testRepeated(){
        String testCaseString = "Hello my name is Qusai Hello Again";
        String outPut = hashTable.repeatedWord(testCaseString);
        assertEquals("hello" , outPut);
    }


    // Test with punctuation

    @Test
    public void testWithPunctuation(){
        String testCaseString = "Hello, my, name. is Qusai Hello Again";
        String outPut = hashTable.repeatedWord(testCaseString);
        assertEquals("hello" , outPut);
    }

    // Test no repeated words

    @Test
    public void noRepeatedTest(){
        String testCaseString = "Hello, my, name. is Qusai Again";
        String outPut = hashTable.repeatedWord(testCaseString);
        assertNull(outPut);
    }
}
